# Generated by Django 4.2.6 on 2023-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='img',
            field=models.ImageField(default='ggg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
