# Generated by Django 4.2.6 on 2023-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressapp', '0002_dress_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='price',
            field=models.IntegerField(default='700'),
            preserve_default=False,
        ),
    ]
